apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgsql-exporter
  template:
    metadata:
      labels:
        app: pgsql-exporter
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: pgsql-exporter
          image: registry.genesi.lan/c.ciacio/pgsql-exporter:2.0
          env:
            - name: DBNAME
              value: "dev"
            - name: USER
              value: "dev"
            - name: PORT
              value: "5432"
            - name: PASSWD
              value: "krnllnx"
            - name: HOST
              value: "cnpg-17-rw-pooler.cnpg"
            - name: SCRAPING
              value: "60"
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: pgsql-exporter
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app: pgsql-exporter
  ports:
    - port: 8080
      targetPort: 8080
